name: humble_arm32 build (EOL)

on:
  push:
    branches: [ ros2 ]
  pull_request:
    branches: [ ros2 ]
  workflow_dispatch: 
                            
jobs:
  humble_arm32_build:
    runs-on: ubuntu-22.04-ARM32
    container:
      image: mesonbuild/bionic:latest
    steps:
      - name: install QEMU
        run: |
          sudo apt update
          sudo apt install -y qemu-system
          sudo apt install -y qemu qemu-user-static
          sudo docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          sudo docker pull rclex/arm32v7_ros_docker:humble
          sudo docker run rclex/arm32v7_ros_docker:humble

      - name: source ros2
        run: |
          source ~/ros2_ws/install/local_setup.bash

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check container status
        run: docker ps -a

      - name: Build and test ROS 2
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: mocap_nokov
          target-ros2-distro: ${{ matrix.ros_distribution }}
          skip-tests: true